#!/usr/bin/env bash
# Configuring domain zone to point to load-balancer

domainz_config() {
    display=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $display" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domainz_config "$1" "www"
  domainz_config "$1" "lb-01"
  domainz_config "$1" "web-01"
  domainz_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  domainz_config "$1" "$2"
fi
